### ISSUE TITLE
not working for bookshelf save()

### ISSUE THREAD

**Issue by mezod** [jpstone/bookshelf-camelcase#1]
Hello, thanks for this great plugin.

I just realized that while it works for my GET endpoints, (where I use fetch/fetchAll) it doesn't for my POST/PUT endpoints, where I use save(). When I do something like 

```
 * add(params) {
    return yield new List(params)
    .save()
    .then(list => list.toJSON());
 },
```

list has all its db snake_case variables still in snake_case. Could this be a bug, or you don't use save() for POST/PUT? Thank you!

**Comment by jpstone** [comment]
Can you try using .set()? Like so:

`add(params) {
    return yield new List()
    .set(params)
    .save()
    .then(list => list.toJSON());
 }
`

**Comment by jpstone** [comment]
Strange. It works just fine for me. Here's an example that I'm using:

```
exports.create = function (req, res, next) {
  SomeModel.forge(req.body)
  .save()
  .then(function (result) {
    return res.status(200).json(result.toJSON()); // <-- this returns all fields as camelCase using the plugin for me
  })
  .catch(function (err) {
    return next(err);
  });
};
```

**Comment by miguelcobain** [comment]
From http://bookshelfjs.org/#Model-instance-parse

> The parse method is called whenever a model's data is returned in a fetch call.

Does this mean that `save` calls are excluded?
I'm also seeing this problem.

**Comment by mezod** [comment]
How could I debug this? My project is in github so you could see it by yourself if you want to try it out? I just don't know what else to try, I have 6 different .save (3 post and 3 put) who are behaving that way :f

**Comment by jpstone** [comment]
I'm going to run some tests and sort it out. In the mean time, you can get around this by doing one extra query:

```
add(params) {
    return yield new List(params)
    .save()
    .then(list => return List.where({id: list.id})
      .fetch();
    )
    .then(list => list.toJSON());
 }
```

**Comment by mezod** [comment]
Thanks, I'll be on all day tomorrow in case you want me to try something out. I'll leave you an url to one of my cases where it doesn't work in case you want to check out for any diffs: https://github.com/mezod/listlogs/blob/joan/api/src/methods/logs.js#L4

Thanks again!

**Comment by mezod** [comment]
Apparently it was bookshelf's fault: https://github.com/tgriesser/bookshelf/issues/25

fixed it adding 

```
 hasTimestamps: ['createdAt', 'updatedAt']
```

to the model. Thanks!
