### ISSUE TITLE
Doesn't convert column names passed in fetch

### ISSUE THREAD

**Issue by nerdpad** [jpstone/bookshelf-camelcase#2]
This doesn't convert column names passed in options to snake case?

``` javascript
getAll() {
        return this.model
            .fetchAll({
                columns: ['id', 'userId', 'name', 'email', 'preference'], // userId doesn't work, user_id does
                withRelated: ['role']
            })
            .then((users) => users.toJSON());
    }
```

**Comment by jpstone** [comment]
Are `columns` and `withRelated` even valid options for `model.fetchAll()`?

http://bookshelfjs.org/#Model-instance-fetchAll

The only options I see are `require` and `transacting`.

**Comment by nerdpad** [comment]
I think so. fetchAll is an alias for Collection query.

Also `.where({roleId: roleId})` doesn't get parsed to `role_id`

Please look at this https://github.com/tgriesser/bookshelf/issues/37#issuecomment-119185236

**Comment by jpstone** [comment]
Hmmm. Strange the documentation doesn't line up.

I take a different approach in my bookshelf projects with this plugin. I've got it working with as follows:

```
getAll() {
  return User.collection()
  .fetch({
    columns: [...],
    withRelated: [...]
  })
  .then((users) => users.toJSON());
}
```

**Comment by jpstone** [comment]
Closing this since there hasn't been a response in 2 weeks.

**Comment by javiercbk** [comment]
I've tested the following

```js
getAll() {
  return User.collection()
  .fetch({})
  .then((users) => users.toJSON());
}
```

Properties are snake_cased

**Comment by javiercbk** [comment]
I've found that the issue only happens when running my tests. Although camel-case was working in the app, test cases are failing somehow.
