### ISSUE TITLE
Do not use strict version for peerDependencies

### ISSUE THREAD

**Issue by gajus** [jpstone/bookshelf-camelcase#4]
Installing any version that is not 0.10.0 is now causing an error.

https://github.com/jpstone/bookshelf-camelcase/blob/3d1d4352cbd7c3ccda72d3f70622cafb5eab4254/package.json#L24

**Comment by jpstone** [comment]
Should be fixed. Published update to npm.

**Comment by gajus** [comment]
Thank you
