### ISSUE TITLE
Timestamps fields not parsed on create/update

### ISSUE THREAD

**Issue by denneulin** [jpstone/bookshelf-camelcase#7]
I have models where I set `hasTimestamps` to true.

Then, when I call create method, the object returned in well camel cased excepted for created_at and updated_at fields.

The same issue happens for updated fields returned by update operation.

**Comment by jpstone** [comment]
Have you taken a look at this issue?

https://github.com/tgriesser/bookshelf/issues/25

As noted in commment the comment here:

https://github.com/jpstone/bookshelf-camelcase/issues/1#issuecomment-162114300

Try setting `hasTimestamps` to `hasTimestamps: ['createdAt', 'updatedAt']` (or whatever you have named those fields)

**Comment by denneulin** [comment]
Oh great this solved my issue.

Thanks a lot ;)
